In [4]:
def solution(board, moves):
    box = []
    answer = 0
    for x in moves:
        for y in range(len(board)):
            if board[y][x-1]:
                if box and board[y][x-1] == box[-1]:
                    answer += 2
                    box.pop()
                    board[y][x - 1] = 0
                    break
                else:
                    box.append(board[y][x-1])
                    board[y][x - 1] = 0
                    break

    return answer

print(solution(1, 2))

TypeError: 'int' object is not iterable

In [ ]:
게임개발자인 "죠르디"는 크레인 인형뽑기 기계를 모바일 게임으로 만들려고 합니다.
"죠르디"는 게임의 재미를 높이기 위해 화면 구성과 규칙을 다음과 같이 게임 로직에 반영하려고 합니다.

crane_game_101.png

게임 화면은 "1 x 1" 크기의 칸들로 이루어진 "N x N" 크기의 정사각 격자이며 위쪽에는 크레인이 있고 오른쪽에는 바구니가 있습니다. (위 그림은 "5 x 5" 크기의 예시입니다). 각 격자 칸에는 다양한 인형이 들어 있으며 인형이 없는 칸은 빈칸입니다. 모든 인형은 "1 x 1" 크기의 격자 한 칸을 차지하며 격자의 가장 아래 칸부터 차곡차곡 쌓여 있습니다. 게임 사용자는 크레인을 좌우로 움직여서 멈춘 위치에서 가장 위에 있는 인형을 집어 올릴 수 있습니다. 집어 올린 인형은 바구니에 쌓이게 되는 데, 이때 바구니의 가장 아래 칸부터 인형이 순서대로 쌓이게 됩니다. 다음 그림은 [1번, 5번, 3번] 위치에서 순서대로 인형을 집어 올려 바구니에 담은 모습입니다.

crane_game_102.png

만약 같은 모양의 인형 두 개가 바구니에 연속해서 쌓이게 되면 두 인형은 터뜨려지면서 바구니에서 사라지게 됩니다. 위 상태에서 이어서 [5번] 위치에서 인형을 집어 바구니에 쌓으면 같은 모양 인형 두 개가 없어집니다.

crane_game_103.gif

크레인 작동 시 인형이 집어지지 않는 경우는 없으나 만약 인형이 없는 곳에서 크레인을 작동시키는 경우에는 아무런 일도 일어나지 않습니다. 또한 바구니는 모든 인형이 들어갈 수 있을 만큼 충분히 크다고 가정합니다. (그림에서는 화면표시 제약으로 5칸만으로 표현하였음)

게임 화면의 격자의 상태가 담긴 2차원 배열 board와 인형을 집기 위해 크레인을 작동시킨 위치가 담긴 배열 moves가 매개변수로 주어질 때, 크레인을 모두 작동시킨 후 터트려져 사라진 인형의 개수를 return 하도록 solution 함수를 완성해주세요.

[제한사항]
board 배열은 2차원 배열로 크기는 "5 x 5" 이상 "30 x 30" 이하입니다.
board의 각 칸에는 0 이상 100 이하인 정수가 담겨있습니다.
0은 빈 칸을 나타냅니다.
1 ~ 100의 각 숫자는 각기 다른 인형의 모양을 의미하며 같은 숫자는 같은 모양의 인형을 나타냅니다.
moves 배열의 크기는 1 이상 1,000 이하입니다.
moves 배열 각 원소들의 값은 1 이상이며 board 배열의 가로 크기 이하인 자연수입니다.
입출력 예
board	moves	result
[[0,0,0,0,0],[0,0,1,0,3],[0,2,5,0,1],[4,2,4,4,2],[3,5,1,3,1]]	[1,5,3,5,1,2,1,4]	4
입출력 예에 대한 설명
입출력 예 #1

인형의 처음 상태는 문제에 주어진 예시와 같습니다. 크레인이 [1, 5, 3, 5, 1, 2, 1, 4] 번 위치에서 차례대로 인형을 집어서 바구니에 옮겨 담은 후, 상태는 아래 그림과 같으며 바구니에 담는 과정에서 터트려져 사라진 인형은 4개 입니다.

crane_game_104.jpg

In [1]:
import yfinance as yf

In [2]:
import pandas as pd

In [2]:
yf.download('AAPL', )

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1980-12-12,0.128348,0.128906,0.128348,0.128348,0.100326,469033600
1980-12-15,0.122210,0.122210,0.121652,0.121652,0.095092,175884800
1980-12-16,0.113281,0.113281,0.112723,0.112723,0.088112,105728000
1980-12-17,0.115513,0.116071,0.115513,0.115513,0.090293,86441600
1980-12-18,0.118862,0.119420,0.118862,0.118862,0.092911,73449600
...,...,...,...,...,...,...
2022-04-11,168.710007,169.029999,165.500000,165.750000,165.750000,72246700
2022-04-12,168.020004,169.869995,166.639999,167.660004,167.660004,79265200
2022-04-13,167.389999,171.039993,166.770004,170.399994,170.399994,70618900
2022-04-14,170.619995,171.270004,165.039993,165.289993,165.289993,75237500
2022-04-18,163.919998,166.598404,163.690002,165.070007,165.070007,69023941

In [8]:
apple = yf.Ticker("AAPL")

카운트를 거면 최근 1000개의 데이트 데이터를 갖고 올수 있다.

In [4]:
sam = yf.Ticker('005930.KS')
sam.history(count=1000)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-03-21,70900.0,71000.0,69900.0,69900.0,11169002,0,0
2022-03-22,69900.0,70500.0,69900.0,70300.0,9402666,0,0
2022-03-23,70600.0,71200.0,70300.0,70500.0,12398025,0,0
2022-03-24,69600.0,70300.0,69600.0,69800.0,37943357,0,0
2022-03-25,70100.0,70200.0,69600.0,69800.0,12986010,0,0
2022-03-28,69500.0,69900.0,69200.0,69700.0,12619289,0,0
2022-03-29,70000.0,70300.0,69800.0,70200.0,13686208,0,0
2022-03-30,70300.0,70500.0,69800.0,69900.0,12670187,0,0
2022-03-31,69900.0,70200.0,69600.0,69600.0,12510366,0,0
2022-04-01,69500.0,69500.0,69000.0,69100.0,15916846,0,0
2022-04-04,68900.0,69300.0,68600.0,69300.0,11107905,0,0
2022-04-05,69400.0,69600.0,69100.0,69200.0,8467248,0,0
2022-04-06,68600.0,68800.0,68500.0,68500.0,15517308,0,0
2022-04-07,68500.0,68500.0,68000.0,68000.0,20683327,0,0
2022-04-08,68100.0,68300.0,67700.0,67800.0,15453191,0,0
2022-04-11,67800.0,68100.0,67400.0,67900.0,12263735,0,0
2022-04-12,67600.0,67700.0,67000.0,67000.0,13924389,0,0
2022-04-13,67300.0,69000.0,67200.0,68700.0,17378619,0,0
2022-04-14,68700.0,68700.0,67500.0,67500.0,16409494,0,0
2022-04-15,67200.0,67300.0,66500.0,66600.0,13176415,0,0
2022-04-18,66600.0,66600.0,66600.0,66600.0,0,0,0
2022-04-19,67100.0,67800.0,67000.0,67700.0,2226698,0,0

In [16]:
apple.history(count = 1000)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2022-02-22,164.979996,166.690002,162.149994,164.320007,91162800,0,0
2022-02-23,165.539993,166.149994,159.750000,160.070007,90009200,0,0
2022-02-24,152.580002,162.850006,152.000000,162.740005,141147500,0,0
2022-02-25,163.839996,165.119995,160.869995,164.850006,91974200,0,0
2022-02-28,163.059998,165.419998,162.429993,165.119995,94869100,0,0
2022-03-01,164.699997,166.600006,161.970001,163.199997,83474400,0,0
2022-03-02,164.389999,167.360001,162.949997,166.559998,79724800,0,0
2022-03-03,168.470001,168.910004,165.550003,166.229996,76678400,0,0
2022-03-04,164.490005,165.550003,162.100006,163.169998,83737200,0,0
2022-03-07,163.360001,165.020004,159.039993,159.300003,96418800,0,0
2022-03-08,158.820007,162.880005,155.800003,157.440002,131148300,0,0
2022-03-09,161.479996,163.410004,159.410004,162.949997,91454900,0,0
2022-03-10,160.199997,160.389999,155.979996,158.520004,105342000,0,0
2022-03-11,158.929993,159.279999,154.500000,154.729996,96836300,0,0
2022-03-14,151.449997,154.119995,150.100006,150.619995,108732100,0,0
2022-03-15,150.899994,155.570007,150.380005,155.089996,92964300,0,0
2022-03-16,157.050003,160.000000,154.460007,159.589996,102300200,0,0
2022-03-17,158.610001,161.000000,157.630005,160.619995,75615400,0,0
2022-03-18,160.509995,164.479996,159.759995,163.979996,123351200,0,0
2022-03-21,163.509995,166.350006,163.009995,165.380005,95722200,0,0

In [13]:
result = apple.history(period= 'max')
# result.to_csv("appl.scv")

In [14]:
import mod_sql
_db = mod_sql.Database()

result.index

ModuleNotFoundError: No module named 'mod_sql'

In [15]:
result.index

DatetimeIndex(['1980-12-12', '1980-12-15', '1980-12-16', '1980-12-17',
               '1980-12-18', '1980-12-19', '1980-12-22', '1980-12-23',
               '1980-12-24', '1980-12-26',
               ...
               '2022-03-08', '2022-03-09', '2022-03-10', '2022-03-11',
               '2022-03-14', '2022-03-15', '2022-03-16', '2022-03-17',
               '2022-03-18', '2022-03-21'],
              dtype='datetime64[ns]', name='Date', length=10406, freq=None)

In [17]:
list(result.Open)

[0.10032309591770171,
 0.09552534544112033,
 0.08854598584692279,
 0.09029065072536469,
 0.09290839731693268,
 0.09857844561338425,
 0.10337623953819275,
 0.10773856192827225,
 0.11340868473052979,
 0.12387729436159134,
 0.12562191486358643,
 0.12300501972579855,
 0.11951567835463878,
 0.12038808315992355,
 0.11820719576657451,
 0.11297254142908608,
 0.10817472492683201,
 0.10599393584792241,
 0.111227847635746,
 0.11122787808958433,
 0.10686629887524543,
 0.1068662777543068,
 0.10904709994792938,
 0.10861094921633539,
 0.11471716314554214,
 0.11166401065396721,
 0.11340868473052979,
 0.11471716314554214,
 0.1147171842889454,
 0.11297254142908608,
 0.1125363715272395,
 0.10861094921633539,
 0.10468548408889679,
 0.09945077186534176,
 0.09334455474006167,
 0.09639766812324524,
 0.09988693147897719,
 0.09988693147897719,
 0.10032309591770171,
 0.09596150280084838,
 0.09508918225765228,
 0.09247221085194011,
 0.09159989333291149,
 0.08985447042224769,
 0.09116294980049133,
 0.09508918225765228,
 0.08985448506267013,
 0.08505671343211597,
 0.08592905104160309,
 0.08374822789220096,
 0.0881098285317421,
 0.08941832184791565,
 0.09247221797704697,
 0.09290839731693268,
 0.09203603725864364,
 0.09116295014155748,
 0.09072681398007681,
 0.09029064245368419,
 0.08287591524841678,
 0.07894971272206326,
 0.0763327322120666,
 0.07851355522871017,
 0.07807736132199207,
 0.08069510757923126,
 0.08462055027484894,
 0.08985447883605957,
 0.08941830727855937,
 0.08985447883605957,
 0.09334453195333481,
 0.09334455474006167,
 0.09203605648422934,
 0.08985448506267013,
 0.08680133549515351,
 0.08636517822742462,
 0.0863651846754609,
 0.08505671343211597,
 0.09203605353832245,
 0.09247221797704697,
 0.09116295014155748,
 0.0902906361968494,
 0.09421684592962264,
 0.09596148878335953,
 0.09726998209953307,
 0.09726998209953307,
 0.09726998209953307,
 0.09290838114801098,
 0.08767366441519087,
 0.08985447883605957,
 0.09596148878335953,
 0.09945075958967207,
 0.10206773132085799,
 0.10206773198889815,
 0.10075925908475594,
 0.099014608739363,
 0.09770613943940612,
 0.09901460260152817,
 0.09901460260152817,
 0.099014608739363,
 0.09857844007925537,
 0.09596148160803901,
 0.09683382511138915,
 0.097706139087677,
 0.09596148160803901,
 0.09552532434463501,
 0.09552534544112033,
 0.09465302438107272,
 0.09596148878335953,
 0.097706139087677,
 0.09639765190311543,
 0.09901460260152817,
 0.10468550026416779,
 0.1094832494854927,
 0.10948325149509344,
 0.11515337228775024,
 0.11515337228775024,
 0.11558953672647476,
 0.11558953672647476,
 0.11035559955625808,
 0.10991943627595901,
 0.11210015416145325,
 0.11079171495194305,
 0.10686629887524543,
 0.10861091315746307,
 0.10991943627595901,
 0.11471716314554214,
 0.11384484787817135,
 0.11340872831053657,
 0.11122788360921011,
 0.10948325149509344,
 0.10904707625735058,
 0.10599393584792241,
 0.10206771832215784,
 0.10337623953819275,
 0.10163157918645999,
 0.10294003039598465,
 0.10250388140965964,
 0.09901460318074823,
 0.09116295014155748,
 0.0902906361968494,
 0.08985447883605957,
 0.08767367814832365,
 0.08767365664243698,
 0.09116294980049133,
 0.08462058057874933,
 0.07807736132199207,
 0.0793866217136383,
 0.08287590742111206,
 0.08505672961473465,
 0.08723750710487366,
 0.09029065072536469,
 0.08462058057874933,
 0.08418441446852273,
 0.0798227815619718,
 0.08113127946853638,
 0.08374825119972229,
 0.08723750710487366,
 0.08462058057874933,
 0.08331207056852627,
 0.08592905104160309,
 0.08723750710487366,
 0.08723749858662116,
 0.08767365664243698,
 0.09029065072536469,
 0.08854598584692279,
 0.0881098285317421,
 0.0881098285317421,
 0.0863651846754609,
 0.08418441446852273,
 0.08156744268578292,
 0.08069512165978784,
 0.07807732987582461,
 0.0763327322120666,
 0.07546041831328922,
 0.07546041160821915,
 0.07109878843092067,
 0.06630028674244483,
 0.06760954111814499,
 0.06673640036709948,
 0.06673642247915268,
 0.07022646814584732,
 0.07022646814584732,
 0.0745880976319313,
 0.07589656114578247,
 0.07284343131233563,
 0.07153495430667403,
 0.06935416031413966,
 0.06891799718141556,
 0.06935416162014008,
 0.06891801250036576,
 0.06673640036709948,
 0.06499179500245225,
 0.06368329244212466,
 0.06193867958775723,
 0.06193864718079567,
 0.062374815344810486,
 0.059321679403556475,
 0.058449398138632716,
 0.05757705530059299,
 0.050597700115379785,
 0.050161547958850854,
 0.052778497338294976,
 0.0532146692276001,
 0.0532146692276001,
 0.05757707729935646,
 0.059321675449609756,
 0.059321679403556475,
 0.062374815344810486,
 0.06455563753843307,
 0.06499174982309341,
 0.06717337667942047,
 0.06717337667942047,
 0.06368329244212466,
 0.06455563753843307,
 0.06411944356452622,
 0.06499174982309341,
 0.06848185509443283,
 0.06848185509443283,
 0.06848186887430753,
 0.06673640036709948,
 0.06630024313926697,
 0.06760954111814499,
 0.06979033350944519,
 0.06935416031413966,
 0.06979033350944519,
 0.06979033350944519,
 0.06935416031413966,
 0.06760953994448313,
 0.06281097851088342,
 0.06281095743179321,
 0.06368328630924225,
 0.06411942839622498,
 0.06586412340402603,
 0.0680457055568695,
 0.06368329244212466,
 0.06281097851088342,
 0.06368328630924225,
 0.06586412340402603,
 0.06586412340402603,
 0.06630024313926697,
 0.0641194497394118,
 0.06324711462775388,
 0.06411942839622498,
 0.06586412340402603,
 0.06542791280765298,
 0.06499174982309341,
 0.06542792916297913,
 0.06499179500245225,
 0.06630024313926697,
 0.06673642247915268,
 0.06630024952641891,
 0.06586412340402603,
 0.06586412340402603,
 0.06586408643282962,
 0.0641194497394118,
 0.06499174982309341,
 0.0680457055568695,
 0.07371576875448227,
 0.07982280105352402,
 0.07676891123989027,
 0.07764120399951935,
 0.07633271845724234,
 0.07633274793624878,
 0.0737157393890046,
 0.0741519182920456,
 0.07720500975847244,
 0.07720500975847244,
 0.07720501741094804,
 0.0737157393890046,
 0.07240726824409069,
 0.06717334379959407,
 0.06935416162014008,
 0.06542791280765298,
 0.06324711462775388,
 0.06281097851088342,
 0.06542792916297913,
 0.06979033350944519,
 0.07109879702329636,
 0.07022648207827553,
 0.07066264003515244,
 0.0719711109995842,
 0.07240727543830872,
 0.07066262537651487,
 0.06848186183967218,
 0.0680457055568695,
 0.07022646814584732,
 0.07109879702329636,
 0.07109878843092067,
 0.07066264003515244,
 0.07066264003515244,
 0.06935416031413966,
 0.06891799718141556,
 0.06499179500245225,
 0.06455563753843307,
 0.06542792916297913,
 0.06499179500245225,
 0.06542792916297913,
 0.06455559137206741,
 0.06499174982309341,
 0.06586412340402603,
 0.06586408643282962,
 0.06499179500245225,
 0.06411944356452622,
 0.06411942839622498,
 0.06411944356452622,
 0.06368328630924225,
 0.06411942839622498,
 0.06411942839622498,
 0.06411942839622498,
 0.06324711462775388,
 0.05844935796789522,
 0.05757705530059299,
 0.05757707729935646,
 0.0571409041836991,
 0.056704740971326835,
 0.05365082654280646,
 0.05321466040492751,
 0.05234235775163809,
 0.04972538593267088,
 0.0532146692276001,
 0.058013200759887695,
 0.062374815344810486,
 0.06193867958775723,
 0.05844935796789522,
 0.058013240630865576,
 0.0571409041836991,
 0.058013200759887695,
 0.058885522186756134,
 0.058885522186756134,
 0.06193864718079567,
 0.06193864718079567,
 0.06193864718079567,
 0.06193867958775723,
 0.061066322274119914,
 0.06106630340218544,
 0.061066322274119914,
 0.05626856022402525,
 0.056268591433763504,
 0.05714089795947074,
 0.058885522186756134,
 0.058449398138632716,
 0.05539628009112506,
 0.054960102433245915,
 0.054086996863182184,
 0.053650833666324615,
 0.054960116744041436,
 0.05365082654280646,
 0.05147002880347778,
 0.051033865660428994,
 0.051470015197992325,
 0.0532146692276001,
 0.054960116744041436,
 0.05496006879284749,
 0.05583239719271659,
 0.056704740971326835,
 0.05626856022402525,
 0.054523125445532714,
 0.05321466040492751,
 0.0532146692276001,
 0.05190618612278709,
 0.05059771112590508,
 0.04972538593267088,
 0.049289226882141435,
 0.04928922280669212,
 0.04972537979483604,
 0.050161547958850854,
 0.050161547958850854,
 0.050161537043238655,
 0.049289226882141435,
 0.0488530695438385,
 0.048416904599566095,
 0.0488530695438385,
 0.04798074336186123,
 0.04623609724755609,
 0.04579993709921837,
 0.045799955334228294,
 0.044927626376064685,
 0.04492761939764023,
 0.046672265976667404,
 0.046672265976667404,
 0.046672265976667404,
 0.046672265976667404,
 0.04623609724755609,
 0.045799939744702416,
 0.04492761939764023,
 0.046672265976667404,
 0.047980744391679764,
 0.047980744391679764,
 0.046672269247617575,
 0.04623609724755609,
 0.044927626376064685,
 0.044491466134786606,
 0.04449145813361249,
 0.04230987973488703,
 0.040565255687367116,
 0.04012909531593323,
 0.03882059021236235,
 0.03969291225075722,
 0.04056524857878685,
 0.04318298399448395,
 0.043619148433208466,
 0.044491466134786606,
 0.04623610898852348,
 0.046672265976667404,
 0.04972537979483604,
 0.04972537979483604,
 0.050161547958850854,
 0.04972538593267088,
 0.047544583163336276,
 0.04710842296481132,
 0.045363779571171325,
 0.046672265976667404,
 0.04710842296481132,
 0.04841691255569457,
 0.045799955334228294,
 0.045363779571171325,
 0.043619144221455304,
 0.04318299479295961,
 0.04318298399448395,
 0.04579993709921837,
 0.04623610898852348,
 0.04623609724755609,
 0.04579993709921837,
 0.046672265976667404,
 0.04972537979483604,
 0.04972537979483604,
 0.050161547958850854,
 0.051470015197992325,
 0.053650833666324615,
 0.056268591433763504,
 0.06019404157996178,
 0.06193864718079567,
 0.059321679403556475,
 0.05975785106420517,
 0.06281095743179321,
 0.06150246050102233,
 0.06368328630924225,
 0.06411942839622498,
 0.061066322274119914,
 0.06281095743179321,
 0.06193867958775723,
 0.06324712932109833,
 0.06368328630924225,
 0.06586412340402603,
 0.06586408643282962,
 0.0641194497394118,
 0.06237480444692512,
 0.062374815344810486,
 0.06368328630924225,
 0.06542792916297913,
 0.06542792916297913,
 0.06368329244212466,
 0.06324712932109833,
 0.06411942839622498,
 0.06411942839622498,
 0.06411944356452622,
 0.06455563753843307,
 0.06455560879953934,
 0.06542796588934931,
 0.06586409417901483,
 0.07109882905874211,
 0.07633273357598466,
 0.08200360977200283,
 0.08374824130079427,
 0.08113128027597068,
 0.08200359469494063,
 0.08200355357020045,
 0.08025895965653655,
 0.08200360977200283,
 0.0837482400456808,
 0.08854598869507832,
 0.09072681398007681,
 0.09029064773154985,
 0.08505670695084433,
 0.0854928586367121,
 0.08767365664243698,
 0.08767367982336782,
 0.08854598614659075,
 0.09421684598306694,
 0.0998869213702991,
 0.10730247112973544,
 0.10730244642504251,
 0.10512164139504232,
 0.10075925852119723,
 0.10468550330905388,
 0.10817480569047476,
 0.11515336992404389,
 0.11297251899267066,
 0.11035558733782277,
 0.10468548937491012,
 0.1094832494854927,
 0.10948320227503629,
 0.10773858735422945,
 0.09945077513240295,
 0.1007592269046891,
 0.10294005828070514,
 0.10119541604615281,
 0.10075922470242656,
 0.11122788063980102,
 0.11340868473052979,
 0.1121002099277814,
 0.11079170175883196,
 0.11689879013855038,
 0.11820727378336326,
 0.11384488250368542,
 0.10817476076219165,
 0.10119540916342477,
 0.0998869287994109,
 0.099014608739363,
 0.09857845489696436,
 0.10032309067800259,
 0.1051216634961754,
 0.10468545832360163,
 0.10599394620561572,
 0.10861093768423465,
 0.111664064971206,
 0.11428099937833387,
 0.11340869487027849,
 0.10948326087380757,
 0.10468548408889679,
 0.10424929882175407,
 0.09945077603693316,
 0.10512162138086743,
 0.10555779175568294,
 0.1016315743977514,
 0.0959614991895981,
 0.10032307761962807,
 0.10294003954085686,
 0.10730242729187012,
 0.1077386423662741,
 0.11515329110178092,
 0.11907950994084093,
 0.1164626130256198,
 0.11733489613066135,
 0.1304204761981964,
 0.13042054273808162,
 0.12300500228628404,
 0.12911200322264205,
 0.13303744665350958,
 0.14219763789064638,
 0.14306994405221465,
 0.14263372038709032,
 0.1456868890654809,
 0.14961236808701697,
 0.15571934398363255,
 0.1535385678044838,
 0.1474315746410918,
 0.14612305954428131,
 0.14743154255409766,
 0.1583363673642162,
 0.16226179663207446,
 0.16138940001648722,
 0.15833628628526009,
 0.15528318085854712,
 0.1535385228781245,
 0.15920869398860815,
 0.16226177704901484,
 0.1648794813941407,
 0.16793263532802039,
 0.1631339976608087,
 0.15920865622982797,
 0.1618256052292997,
 0.1631340811165395,
 0.15790020420697934,
 0.15571934462256434,
 0.15179312457688232,
 0.14786765692457726,
 0.15222923808464894,
 0.15004848365729773,
 0.1474315733691582,
 0.1443784338276449,
 0.1465592384338379,
 0.14655920181812854,
 0.14786763138404002,
 0.15004847791890205,
 0.15353852725033393,
 0.15528318679713674,
 0.147867742613377,
 0.15048471093177795,
 0.1500484774312848,
 0.1487400008014191,
 0.15266618380219224,
 0.15441089421259296,
 0.14743149784911194,
 0.1435060904183564,
 0.1408891355991482,
 0.13957986927755522,
 0.138271343866515,
 0.13739901020486253,
 0.14525071801337197,
 0.14830383706603883,
 0.15353857305860058,
 0.1570278709701856,
 0.16051712975109866,
 0.1640064554803135,
 0.16226177114118873,
 0.17883741962821278,
 0.18145435652390973,
 0.17796506373930057,
 0.16967725467756145,
 0.17447499717324233,
 0.17273037332099986,
 0.17447501615528258,
 0.1762196510482182,
 0.1709857415312867,
 0.16924113399535354,
 0.17970968914997631,
 0.19148682317674348,
 0.19235915995925484,
 0.18974215942784187,
 0.19105069927443694,
 0.18625214525260939,
 0.1845075065740852,
 0.18537977552612483,
 0.18058206685516845,
 0.18101825815988187,
 0.18319906078142276,
 0.18886913781343934,
 0.19846541094257097,
 0.20064620013338957,
 0.21111484868838434,
 0.20937017691233425,
 0.2071893960237503,
 0.20675316074359174,
 0.2015192888227747,
 0.20282775983047574,
 0.2041362073333546,
 0.21416873886040283,
 0.2189665963773361,
 0.2115509494852375,
 0.20893403089749707,
 0.20762552055112932,
 0.2067531948718637,
 0.19977388650082162,
 0.19497611564503076,
 0.19061449587186524,
 0.19977386168445066,
 0.19584844791341394,
 0.18625214001214146,
 0.1879968183256766,
 0.1923591185041391,
 0.18712447962280393,
 0.1858159316145267,
 0.17578352385946147,
 0.16357021574775107,
 0.17142195770308713,
 0.1705496239095302,
 0.1718580685474265,
 0.16487949147604752,
 0.16531566783550497,
 0.16313411151626392,
 0.16138942628194483,
 0.16575183815240774,
 0.1618255980035045,
 0.16095328950911542,
 0.16051712729973916,
 0.1548469755384072,
 0.1544108668894177,
 0.15266620550763638,
 0.143942235770115,
 0.15135695626771237,
 0.15266629630394923,
 0.15048457512167823,
 0.13652673256945855,
 0.12649422686824863,
 0.11864339061356141,
 0.12169656154528562,
 0.12038800728478123,
 0.11995186843848307,
 0.12169647434256316,
 0.11602647516882404,
 0.11820718788775252,
 0.11864336665470553,
 0.11995185358438772,
 0.1195156848881898,
 0.1177710565686301,
 0.11689872602462982,
 0.11995191000381758,
 0.11820727378336326,
 0.11558947240660838,
 0.11689871829243542,
 0.1177711027963389,
 0.11733487532928022,
 0.11079169453541637,
 0.105557820898962,
 0.10643008458006797,
 0.10773861036399632,
 0.10904708878549497,
 0.11558949659032881,
 0.12998437184257614,
 0.12693039626609498,
 0.13521821431906378,
 0.13696287093219978,
 0.1208241952572141,
 0.1107917109073386,
 0.1068662777543068,
 0.10686629653818347,
 0.1116640412272256,
 0.11035556514000396,
 0.10512162046201154,
 0.1025039074681288,
 0.11166399121914505,
 0.11210024102997175,
 0.10991940284435539,
 0.08723751174723218,
 0.08505672222902395,
 0.0868013613904223,
 0.08200359965731337,
 0.07982278484004768,
 0.07938662398628371,
 0.08069510757923126,
 0.08069512165978784,
 0.07982281973765193,
 0.0785135244682043,
 0.07764119704013431,
 0.07022648075584854,
 0.0689180192885652,
 0.06760953048764021,
 0.07589653237736643,
 0.08025894214271781,
 0.07938664434230229,
 0.072407302174674,
 0.06760949878835969,
 0.07502423586865133,
 0.07109880253641097,
 0.06935417165637801,
 0.07371575516837758,
 0.07415190651680827,
 0.07022649224074692,
 0.0737157393890046,
 0.07371575260441522,
 0.07894964987152603,
 0.08025895965653655,
 0.08200361632251338,
 0.07633273050758897,
 0.07371577664391302,
 0.0680456819424488,
 0.06237482950113085,
 0.06717337122915283,
 0.06848185546090367,
 0.06979031762312445,
 0.06891799718141556,
 0.06891801286917063,
 0.06979033504426502,
 0.07153494793133926,
 0.07197109966523105,
 0.07502421736717224,
 0.07502423586865133,
 0.07109881894532319,
 0.0715349778614609,
 0.07327959583773187,
 0.07240727469716836,
 0.07109880318003826,
 0.07066263939547353,
 0.0693541562423077,
 0.07109881894532319,
 0.0715349778614609,
 0.0732795770164237,
 0.07502425421816562,
 0.07546037454299061,
 0.07502427198691833,
 0.07851353125917476,
 0.08156744698769734,
 0.08505670060049918,
 0.08636521334130151,
 0.08374823490514949,
 0.08156743146893831,
 0.08462053750903152,
 0.08636521431532256,
 0.08592901513595695,
 0.08636518666049993,
 0.08723752834476259,
 0.08505672961473465,
 0.08505672464281337,
 0.08985447452690944,
 0.09726997370666564,
 0.09857846040588322,
 0.09683379597848944,
 0.09159990211734106,
 0.09639766124902849,
 0.09770613943940612,
 0.09726998652751251,
 0.09508917792894866,
 0.09726997028634302,
 0.09988694439812705,
 0.10032309105276317,
 0.10119540916342477,
 0.09988693827271013,
 0.10075926287655686,
 0.09508916632667255,
 0.09421686380499603,
 0.09639765887870995,
 0.09116293729113623,
 0.08636517822742462,
 0.08636521431532256,
 0.08592903698629703,
 0.08680134197575334,
 0.08549288252229953,
 0.08113129736600697,
 0.08418440451804081,
 0.0811312741414645,
 0.08243976764445667,
 0.08505671343211597,
 0.08462056142805889,
 0.08941829737651243,
 0.08767367982336782,
 0.0885459848595646,
 0.08723751055732856,
 0.09159987985530542,
 0.09552534491950551,
 0.09378066043139066,
 0.09465300904001711,
 0.09421685312152213,
 0.08898213292747108,
 0.09159988473847293,
 0.0942168617144562,
 0.09508917286744084,
 0.09334454139850004,
 0.08985447604134496,
 0.09247222012312074,
 0.09378069444027191,
 0.09247220020585213,
 0.09552532943706701,
 0.0942168754100605,
 0.09290837463667802,
 0.09334455474006167,
 0.09247219449511218,
 0.09159989367561237,
 0.09072679281234741,
 0.09072679088588484,
 0.08898214995861053,
 0.0889821582907399,
 0.08985446843799487,
 0.08767366635128507,
 0.08898216363175708,
 0.0885459762135466,
 0.0863652001886738,
 0.08680134397081712,
 0.08723750509978499,
 0.08549290138193492,
 0.0841844053558604,
 0.08200360089540482,
 0.08374821714983498,
 0.0863651846754609,
 0.08549287610946116,
 0.08985447883605957,
 0.08985445322414654,
 0.09334452753604154,
 0.09596149808698584,
 0.09770613100890517,
 0.0985784395025868,
 0.09901461728276498,
 0.0972699886857969,
 0.09683384185388515,
 0.10381316456580689,
 0.10512165256154855,
 0.11079168805289286,
 0.1160264793175632,
 0.11515332303339826,
 0.11035556514000396,
 0.10512163165331846,
 0.10904708878549497,
 0.1147172100696624,
 0.11558953672647476,
 0.11558950912718634,
 0.11210020436486688,
 0.11035553324677919,
 0.11122789601201706,
 0.10643010628320912,
 0.10163160867042934,
 0.10381313456336354,
 0.11122784262180034,
 0.107738576429509,
 0.1055577835154649,
 0.10250386736823036,
 0.10294003646129408,
 0.10250389513480165,
 0.1011953958949572,
 0.10250393013527918,
 0.10599397595837748,
 0.10163158461696216,
 0.09726997815013619,
 0.10119542225181016,
 0.10032308294214103,
 0.09988693147897719,
 0.09988692617960371,
 0.10206776028978799,
 0.10381316362159963,
 0.10075925419866666,
 0.10119543507407591,
 0.10337619951474744,
 0.1025038743038152,
 0.10555780588973974,
 0.10119540916342477,
 0.09988694815710077,
 0.09508917560425124,
 0.09072678989404451,
 0.08810982821598913,
 0.0920360606298228,
 0.09247222726119156,
 0.0894183063010236,
 0.08810981894581771,
 0.08636517900374982,
 0.08767364957058872,
 0.09159989958468795,
 0.09378070166619916,
 0.09247223407006284,
 0.09290837398929717,
 0.09203606349239053,
 0.08985447883605957,
 0.08985448422943647,
 0.08854600042104721,
 0.08854600042104721,

In [13]:
import yfinance as yf

sam = yf.download('005930.KS', period='2y', count = 100)
sam

[*********************100%***********************]  1 of 1 completed

               Open     High      Low    Close     Adj Close    Volume
Date
2020-04-20  51400.0  51400.0  50000.0  50100.0  47383.281250  21866354
2020-04-21  49400.0  49700.0  48700.0  49250.0  46579.378906  27407543
2020-04-22  48700.0  50000.0  48350.0  49850.0  47146.839844  18613864
2020-04-23  50200.0  50300.0  49500.0  49850.0  47146.839844  18754442
2020-04-24  49650.0  49750.0  49000.0  49350.0  46673.945312  15618347
...             ...      ...      ...      ...           ...       ...
2022-04-13  67300.0  69000.0  67200.0  68700.0  68700.000000  17378619
2022-04-14  68700.0  68700.0  67500.0  67500.0  67500.000000  16409494
2022-04-15  67200.0  67300.0  66500.0  66600.0  66600.000000  13176415
2022-04-18  66600.0  66600.0  66600.0  66600.0  66600.000000         0
2022-04-19  67100.0  68000.0  67000.0  67800.0  67800.000000   9377009

[493 rows x 6 columns]

삼성전자에 대한 주가 를 불러 온다. 
기간은 1년치 
그리고 주가에 소수점 2째자리만 남긴다. 
널값이 있는지 한번 확인해주고

종가 - 시가를 해서 등락폭을 만들어준다. 
등락폭 / 시가를 해서 등락율을 만들어 준다.

In [26]:
import yfinance as yf
 
sam = yf.Ticker('005930.KS')
sam.history( start = '2021-04-01', end= '2022-04-01')
sam_dt = sam.history(  start = '2021-04-01', end= '2022-04-01')
sam_dt = sam_dt.round(2)
sam_dt.isna().sum()

# sam_dt.columns[ "시가", "고가", "저가", "종가", "거래량", "시가총액"]
sam_dt["등락폭"] = sam_dt["Close"] - sam_dt["Open"]
sam_dt['등락율'] = sam_dt["등락폭"] / sam_dt["Open"] * 100
sam_dt

,Open,High,Low,Close,Volume,Dividends,Stock Splits,등락폭,등락율
Date,,,,,,,,,
2021-04-01,81380.23,81873.45,80887.02,81774.80,18676461,0.0,0,394.57,0.484847
2021-04-02,82859.87,84043.59,82761.23,83649.02,22997538,0.0,0,789.15,0.952391
2021-04-05,84635.45,84832.73,83649.02,84240.88,16255990,0.0,0,-394.57,-0.466199
2021-04-06,85030.01,85030.01,83944.94,84832.73,19042023,0.0,0,-197.28,-0.232012
2021-04-07,84931.37,85030.01,84240.87,84438.16,17885538,0.0,0,-493.21,-0.580716
...,...,...,...,...,...,...,...,...,...
2022-03-25,70100.00,70200.00,69600.00,69800.00,12986010,0.0,0,-300.00,-0.427960
2022-03-28,69500.00,69900.00,69200.00,69700.00,12619289,0.0,0,200.00,0.287770
2022-03-29,70000.00,70300.00,69800.00,70200.00,13686208,0.0,0,200.00,0.285714
2022-03-30,70300.00,70500.00,69800.00,69900.00,12670187,0.0,0,-400.00,-0.568990
2022-03-31,69900.00,70200.00,69600.00,69600.00,12510366,0.0,0,-300.00,-0.429185

import yfinance as yf

apple = yf.Ticker("AAPL")
apple.history(period = 'max')
result = apple.history(period = 'max')

_df = _df.round(2)
_df.isna().sum()
_df.fillna("bfill")
_df["등락폭"] = _df["Close"] - _df["Open"]
_df['등락율'] = _df["등락폭"] / _df["Open"] * 100

In [ ]:
import mod_sql

_db = mod_sql.Database()

_sql = """
        SELECT *
        FROM apple

"""

result = _db.executeAll(_sql)
_df = pd.DataFrame(result)

_df = _df.roun

import yfinance as yf

apple = yf.Ticker("AAPL")
apple.history(period = 'max')
result = apple.history(period = 'max')
result.to_csv("apple.csv")

import mod_sql
_db = mod_sql.Database()

_sql = """
        SELECT * 
        FROM apple

"""
ressult = _db.executeAll(_sql)
_df = pd.DataFrame(result)

_df = _df.round(2)
_df.isna().sum()
_df.fillna("bfill")
_df["등락폭"] = _df["Close"] - _df["Open"]
_df['등락율'] = _df["등락폭"] / _df["Open"] * 100

import matplotlib as plt

plt.plot(_df["Open"])

plt.subplot(2,2,1)
plt.plot(_df["Open"])
plt.subplot(2,2,1)
plt.plot(["Close"])
plt.subplot(2,2,1)

plt.subplot(2,2,1)

In [ ]:
import yfinance as yf
import pandas as pd
import mod_sql

apple = yf.Ticker('AAPL')
apple.history(period = 'max')
resutl = apple.history(period = 'max')
result.to_csv('apple.csv')

_db = mod_sql.Database()

_sql = '''
        SELECT *
        FROM apple


'''
result = _db.executeAll(_sql)
_df = pd.DataFrame(result)

_df = _df.round(2)
_df.isna().sum()
_df.fillna('bfill')
_df['등락폭'] = _df['Close'] - _df['Open']
_df['등락율'] = _df['등락폭'] / _df['Open'] * 100

import matplotlib.pyplot as plt
plt.plot(_df['Open']
         
plt.subplot(2,2,1)
plt.plot(_df["Open"])
plt.subplot(2,2,2)
plt.plot(_df["Close"])
plt.subplot(2,2,3)
plt.plot(_df["등락폭"])
plt.subplot(2,2,4)
plt.plot(_df["등락율"])

plt.show()

sql 모듈 만들기 - 내 데이터베이스 만들어서 파이썬에 자유롭게 써먹기

import pymysql을 불러 옵니다.

이제 클래스를 만듭니다. 
clss Database(): 로 만들고
함수 def __init(self): 초기 생성자를 만들어 줍니다. 

이제 mysql에 접속할 호스트명과 유저명 비번, 데이터베이스 db를 만들어 줍니다. 

self._db = pypmysql.connect( 
                            host = 'localhost',
                            user = 'root',
                            password = 'kkkkkk'
                            db = 'ubion'
)

그리고 이를 실행해줄 커서를 만들어 줍니다. 
slef.cursor = self._db.cursor(pymysql.cursors.DictCursor)
여기 까지 가 하나의 셋트,

이제 두번째 함수인 실제 sql을 받아와 실행하는 함수를 만듭니다.
def execute(self, _sql, _values={}):
    self.curor.execute(_sql, _values)

executeAll이라는 객체를 하나더 만들어 줍니다. 
def executeAll(self, _sql, _values={}):
    self.cursor.execute(_sql, _values)
    self.resut = self.cursor.fetchall()
    return self.result

그리고 데이터 변화를 주고 실해해 주는 commit을 만들어 줍니다.

def commit(self):
    self._db.commit()

In [ ]:
import pymysql

class Datavase():
    def __init__(self):
        self._db = pymysql.connect(
                                    host:
                                    user:
                                    password:
                                    db
        )
        self.cursor = self._db.cursor(pymysql.cursors.DictCursor)
        
    def execute(self, _sql, _values={}):
        self.cursor.execute(_sql, _values)
        
    def executeAll(self, _sql, _values={}):
        self.cursor.execute(_sql, _values)
        self.result = self.cursor.fetchall()
        return self.result
    
    def commit(self):
        self._db.commit()

In [11]:
import pandas as pd
dt = pd.DataFrame([[1,2,3], [4,5,6], [10, 11, 12], [7,8,9]])

dt.columns = ['A', 'B', 'C']
dt['D'] = (dt['C'] - dt['C'].shift()).fillna(0)

dt.sort_values('A', inplace=True)
dt.reset_index(drop=True, inplace=True)

dt

    A   B   C    D
0   1   2   3  0.0
1   4   5   6  3.0
2   7   8   9 -3.0
3  10  11  12  6.0

In [13]:
exam_data = {'이름' : ['서준','우현','인아'],
            '수학' : [90,80,70],
            '영어' : [98,89,95],
            '음악' : [85,95,100],
            '체육' : [100,90,90]}
df = pd.DataFrame(exam_data)
print(df)
print('\n')

ndf1 = df.set_index('이름')  # '이름'열을 인덱스로 사용
print(ndf1)
print('\n')

ndf2 = ndf1.set_index(['음악']) # '음악'열을 인덱스로 사용
print(ndf2)
print('\n')

ndf3 = ndf1.set_index(['수학','음악']) # '수학','음악'열을 인덱스로 사용
print(ndf3)

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90


    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90


     수학  영어   체육
음악
85   90  98  100
95   80  89   90
100  70  95   90


        영어   체육
수학 음악
90 85   98  100
80 95   89   90
70 100  95   90

In [14]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index = ['r0','r1','r2'])
print(df)

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [15]:
ndf = df.reset_index()
print(ndf)

  index  c0  c1  c2  c3  c4
0    r0   1   4   7  10  13
1    r1   2   5   8  11  14
2    r2   3   6   9  12  15